### ISSUE TITLE
Shortcut for enabling/disabling profiling on DB

### ISSUE THREAD

**Issue by oliverfriedmann** [foodji/mongo-service-profiler#6]
Profiling on the console can be enabled via:
```
db.setProfilingLevel(0)
db.system.profile.drop()
db.createCollection( "system.profile", { capped: true, size:100000000 } )
db.setProfilingLevel(2)
```

And disabled via just:
```
db.setProfilingLevel(0)
```

Since running profiling 24/7 might severely impact performance on production workload, it's beneficial to only activate profiling for a few hours when trying to debug an issue and then deactivating it again. Therefore, it would be great to include `--activate-profiling` and `--deactivate-profiling` as tool commands to `mongostat`. So a debugging session then might be carried out as follows:
```
mongostat --profile prod-db --activate-profiling
... wait a few hours ...
mongostat --profile prod-db --deactivate-profiling
mongostat --profile prod-db --command agg
```

**Comment by kituyiharry** [comment]
Looks like this toggling support for profiling functionality is not directly supported by the current official rust driver.

**Comment by kituyiharry** [comment]
Implemented via run_command from the Rust Mongo library. Usable using the CLI switches suggested :-)
