### ISSUE TITLE
Need to be expanded as strings

### ISSUE THREAD

**Issue by oliverfriedmann** [foodji/mongo-service-profiler#9]
Those fields need to be expanded as strings and not "pruned": `ns, command.find, command.count, planSummary`

**Comment by kituyiharry** [comment]
I already have `planSummary` in the output as a unique set of string for a given command. Should I _expand_ this to a full Vec or leave as is? also should I only collect _Unique_ values of `ns` into a set or leave as is ?

<img width="874" alt="Screen Shot 2022-04-05 at 10 25 25 pm" src="https://user-images.githubusercontent.com/12397823/161776295-aa742b0b-9a26-403b-b201-07dc7fc78501.png">
